name: Deploy WordPress to FTP server

on:
  push:
    branches:
      - main  # O la rama que uses para producción

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install lftp
      run: sudo apt-get install lftp

    - name: Deploy to FTP
      env:
        FTP_HOST: ${{ secrets.FTP_HOST }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      run: |
       lftp -f "
          open ftp://$FTP_USERNAME:$FTP_PASSWORD@$FTP_HOST
          mirror --reverse --delete --verbose ./ /htdocs/
        "
